*** Variables ***
${MESSAGE}                   Hello, world!
${PORTAL}                    172.30.215.27:3002  
${USER}                      imran.ansari@hpe.com
${PASSWORD}                  dummy_password
${MEMBERSHIP}                TestHoster1
${ROLE}                      hoster_owner
${PORTAL_ID}                 TestPortal
${CLUSTER_USER}              mapr
${CLUSTER_PASS}              mapr
${STORAGE_REST_HOST}         https://172.28.220.6:8443 
${STORAGE_ID}                ece
${CDC_REST_URI}              http://172.30.215.73:8000/data-fabric/v1 
${ARRAY_YAML}                array.yml
${FLAVOR_YAML}               volume_flavor.yml
${VOLUME_YAML}               volume.yml
${VOLUME_ATTACHMENT_YAML}    volume_attachment.yml
${POD_NAME}                  L2PODv2-DCC 
${LATENCY_VALUE}             LatencyStandard
${ARRAY_TYPE}                MapR
${STORAGE_ID}                mapr-cluster.perflab.hp.com

