*** Variables ***
${MESSAGE}                   Hello, world!
${PORTAL}                    quake.intg.hpedevops.net  
${USER}                      mahadev.gaonkar@hpe.com
${PASSWORD}                  dummy_password
${PORTAL_ID}                 GLHCIntgPortal
${CLUSTER_USER}              mapr
${CLUSTER_PASS}              mapr
${STORAGE_REST_HOST}         https://172.28.220.6:8443 
${STORAGE_ID}                ece
${CDC_REST_URI}              http://172.28.4.55:8000/data-fabric/v1 
${ARRAY_YAML}                array.yml
${FLAVOR_YAML}               volume_flavor.yml
${VOLUME_YAML}               volume.yml
${VOLUME_ATTACHMENT_YAML}    volume_attachment.yml
${POD_NAME}                  L2PODv2-DCC 
${LATENCY_VALUE}             LatencyHiPerformance

