*** Variables ***
${MESSAGE}                   Hello, world!
${PORTAL}                    172.30.215.27:3002  
${USER}                      imran.ansari@hpe.com
${PASSWORD}                  dummy_password
${MEMBERSHIP}                TestHoster1
${ROLE}                      hoster_owner
${PORTAL_ID}                 TestPortal
${CLUSTER_USER}              ssadmin
${CLUSTER_PASS}              Password?234!
${STORAGE_REST_HOST}         https://172.30.215.36:443 
${STORAGE_ID}                my_ss_cluster.cdc.hpe.com
${CDC_REST_URI}              http://172.30.215.71:8000/data-fabric/v1
${ARRAY_YAML}                array.yml
${FLAVOR_YAML}               volume_flavor.yml
${VOLUME_YAML}               volume.yml
${VOLUME_ATTACHMENT_YAML}    volume_attachment.yml
${POD_NAME}                  L2PODv2-DCC 
${LATENCY_VALUE}             LatencyHiPerformance
${ARRAY_TYPE}                SpectrumScale
${HOST_IP_ADDRESS}           172.30.215.27
